### ISSUE TITLE
[Feqture request] Add a way to custom settings

### ISSUE THREAD

**Issue by lambdalisue** [tsuyoshicho/vim-efm-langserver-settings#75]
I like the idea but I could not use this while it seems this does not provide a patch existing settings. I would be really nice if I can overwrite existing settings by my own local settings somehow.

Or am I missing some features?

**Comment by tsuyoshicho** [comment]
Your request are resolving below setting?

https://github.com/tsuyoshicho/vim-efm-langserver-settings/blob/7738bdabca45331b6c872f399742fee9d42d7398/doc/vim-efm-langserver-settings.jax#L159-L168

**Comment by lambdalisue** [comment]
Probably! Sorry for the noise.
